<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-gabrieltizziani/blob/main/Atividades.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).

**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.


In [ ]:
### 1. Vetor de zeros  _(fácil)_

### Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

import numpy

# Criar um vetor 1D com 10 zeros
array = numpy.zeros(10)

# Exibir o array, dtype e shape
print(array)
print("dtype:", array.dtype)
print("shape:", array.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
dtype: float64
shape: (10,)


In [ ]:
### 2. Vetor de uns  _(fácil)_

### Crie um array 1D com 10 uns e transforme-o em float64.
import numpy as np
np.ones(10, dtype=np.float64)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
### 3. Sequência 0–9  _(fácil)_

### Crie um array com os inteiros de 0 a 9 (inclusive).
import numpy as np
np.arange(10)

#arange cria um array de valores espaçados uniformemente dentro de um intervalo definido


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
### 4. Matriz 3×3 com 0…8  _(fácil)_

### Crie um array 3×3 com os valores 0…8 (reshape).
import numpy as np
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
### 5. Índices não zero  _(fácil)_

### Dado o vetor v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.

