<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-gabrieltizziani/blob/main/Atividade22-10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).

**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.


In [8]:
### 1. Vetor de zeros  _(fácil)_

### Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

import numpy

# Criar um vetor 1D com 10 zeros
array = numpy.zeros(10)

# Exibir o array, dtype e shape
print(array)
print("dtype:", array.dtype)
print("shape:", array.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
dtype: float64
shape: (10,)


In [10]:
### 2. Vetor de uns  _(fácil)_

### Crie um array 1D com 10 uns e transforme-o em float64.
import numpy as np
numpy.ones(10, dtype=np.float64)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
### 3. Sequência 0–9  _(fácil)_

### Crie um array com os inteiros de 0 a 9 (inclusive).
import numpy as np
np.arange(10)

#arange cria um array de valores espaçados uniformemente dentro de um intervalo definido


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
### 4. Matriz 3×3 com 0…8  _(fácil)_

### Crie um array 3×3 com os valores 0…8 (reshape).
import numpy as np
np.arange(9).reshape(3, 3)

In [ ]:
### 5. Índices não zero  _(fácil)_

### Dado o vetor v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.
import numpy as np
v = np.array([1, 2, 0, 0, 4, 0])
elementos_nao_nulos = np.nonzero(v)
print(elementos_nao_nulos)


In [ ]:
### 6. Linspace  _(fácil)_

### Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].
numpy.linspace(0, 1, 12)


In [13]:
### 7. Identidade 5×5  _(fácil)_

### Crie uma matriz identidade de ordem 5.
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
### 8. Aleatórios 3×3×3  _(fácil)_

### Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.
rng = np.random.default_rng(42)
array_3x3x3 = rng.random((3, 3, 3))
print(array_3x3x3)




In [ ]:
### 9. Min/Max  _(fácil)_

### Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.
matriz_10x10 = np.random.rand(10, 10)
min_val = matriz_10x10.min()
max_val = matriz_10x10.max()
print(f"Valor Mínimo: {min_val}")
print(f"Valor Máximo: {max_val}")

In [ ]:
### 10. Padronização 1D  _(fácil)_

### Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

x = np.array([1, 2, 3, 4, 5], dtype=float)
media = x.mean()
desvio = x.std()
x_padronizado = (x - media) / desvio
print(f"Array original: {x}")
print(f"Média original: {x.mean():.2f}, Desvio original: {x.std():.2f}")
print(f"Array padronizado: {x_padronizado}")
print(f"Média padronizada: {x_padronizado.mean():.2f}, Desvio padronizado: {x_padronizado.std():.2f}")

In [14]:
### 11. Conversão de tipos  _(fácil)_

### Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.
arr_int32 = np.array([1, 2, 3])
print(f"Original: {arr_int32}, Tipo: {arr_int32.dtype}")

arr_float32 = arr_int32.astype(np.float32)
print(f"Para float32: {arr_float32}, Tipo: {arr_float32.dtype}")

arr_int64 = arr_float32.astype(np.int64)
print(f"Para int64: {arr_int64}, Tipo: {arr_int64.dtype}")

Original: [1 2 3], Tipo: int64
Para float32: [1. 2. 3.], Tipo: float32
Para int64: [1 2 3], Tipo: int64


In [ ]:
### 12. Clipping  _(fácil)_

### Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).
a = np.array([2, 5, 7, 1, 9])
a_clipped = np.clip(a, 0, 5)
print(f"Array original: {a}")
print(f"Array limitado [0,5]: {a_clipped}")

In [ ]:
### 13. Inversão  _(fácil)_

### Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).

vetor = np.arange(10)
vetor_invertido = np.flip(vetor)
print(f"Vetor original: {vetor}")
print(f"Vetor invertido: {vetor_invertido}")

In [ ]:
### 14. Empilhamento  _(fácil)_

### Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
empilhado_h = np.hstack((a, b))
empilhado_v = np.vstack((a, b))
print(f"a: {a}, b: {b}")
print(f"Horizontal: {empilhado_h}")
print(f"Vertical:\n{empilhado_v}")


In [ ]:
### 15. Diagonal  _(fácil)_

### Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.
diagonal_5 = np.diag([5, 5, 5, 5])
print(diagonal_5)

In [15]:
### 16. Somas por eixo  _(fácil)_

### Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.
A = np.arange(12).reshape(3, 4)
soma_por_colunas = A.sum(axis=0)
soma_por_linhas = A.sum(axis=1)
print(f"Matriz A:\n{A}")
print(f"Soma por colunas (axis=0): {soma_por_colunas}")
print(f"Soma por linhas (axis=1): {soma_por_linhas}")

Matriz A:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Soma por colunas (axis=0): [12 15 18 21]
Soma por linhas (axis=1): [ 6 22 38]


In [16]:
### 17. Frequências inteiras  _(fácil)_

### Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).
rng = np.random.default_rng(42)
dados = rng.integers(0, 10, size=100) # [0, 10)
valores, contagens = np.unique(dados, return_counts=True)

print("Frequências (Valor: Contagem):")
for v, c in zip(valores, contagens):
    print(f"{v}: {c}", end=" | ")
print() # Nova linha


Frequências (Valor: Contagem):
0: 9 | 1: 9 | 2: 6 | 3: 9 | 4: 15 | 5: 7 | 6: 11 | 7: 15 | 8: 12 | 9: 7 | 


In [17]:
### 18. Slicing com passo  _(fácil)_

### Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.
v = np.arange(20)
v_filtrado = v[1::3] # Começa no índice 1, vai até o fim, com passo de 3
print(f"Vetor original: {v}")
print(f"Elementos a partir do índice 1 com passo 3: {v_filtrado}")


Vetor original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elementos a partir do índice 1 com passo 3: [ 1  4  7 10 13 16 19]


In [18]:
# 18. Slicing com passo (fácil)
# Dado v = np.arange(20), selecione cada 3º elemento começando do índice 1.

v = np.arange(20)
v_filtrado = v[1::3]
print(f"Vetor original: {v}")
print(f"Elementos a partir do índice 1 com passo 3: {v_filtrado}")

Vetor original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elementos a partir do índice 1 com passo 3: [ 1  4  7 10 13 16 19]


In [ ]:
# 19. Máscara booleana (fácil)
# Crie uma máscara para números pares de 0…19 e use-a para filtrar o vetor.
vetor_0_19 = np.arange(20)
mascara_par = (vetor_0_19 % 2 == 0)
vetor_pares = vetor_0_19[mascara_par]
print(f"Vetor 0-19: {vetor_0_19}")
# print(f"Máscara booleana: {mascara_par}")
print(f"Números pares: {vetor_pares}")


In [ ]:
# 20. Lista de listas -> array (fácil)
# Converta [[1,2,3],[4,5,6]] em ndarray, verifique shape e dtype.
print("--- 20. Lista de listas -> array ---")
lista_de_listas = [[1, 2, 3], [4, 5, 6]]
array_convertido = np.array(lista_de_listas)
print(f"Lista de listas: {lista_de_listas}")
print(f"Array convertido:\n{array_convertido}")
print(f"Shape: {array_convertido.shape}")
print(f"Dtype: {array_convertido.dtype}")
print("-" * 30)

In [ ]:
# 21. Datas básicas (fácil)
# Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).
print("--- 21. Datas básicas ---")
datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(datas)
print("-" * 30)

In [19]:
# 22. Centralizar colunas (fácil)
# Dada A = np.array([[1.,2.,3.],[4.,5.,6.]]), subtraia a média de cada coluna.
A = np.array([[1., 2., 3.], [4., 5., 6.]])
medias_colunas = A.mean(axis=0)
# Subtrair as médias, o broadcasting funciona automaticamente
A_centralizada = A - medias_colunas
print(f"Matriz A:\n{A}")
print(f"Médias das colunas: {medias_colunas}")
print(f"Matriz A centralizada (Média de cada coluna deve ser ~0):\n{A_centralizada}")
print(f"Novas médias: {A_centralizada.mean(axis=0)}") # Deve ser muito próximo de zero


Matriz A:
[[1. 2. 3.]
 [4. 5. 6.]]
Médias das colunas: [2.5 3.5 4.5]
Matriz A centralizada (Média de cada coluna deve ser ~0):
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
Novas médias: [0. 0. 0.]


In [20]:
# 23. Produto elemento-a-elemento vs. escalar (fácil)
# Dadas a=[1,2,3] e b=[4,5,6], calcule produto elemento a elemento e o produto escalar.
a_prod = np.array([1, 2, 3])
b_prod = np.array([4, 5, 6])

prod_element_a_element = a_prod * b_prod
prod_escalar = np.dot(a_prod, b_prod)

print(f"a: {a_prod}, b: {b_prod}")
print(f"Produto elemento-a-elemento (a * b): {prod_element_a_element}")
print(f"Produto escalar (np.dot(a, b)): {prod_escalar}")

a: [1 2 3], b: [4 5 6]
Produto elemento-a-elemento (a * b): [ 4 10 18]
Produto escalar (np.dot(a, b)): 32


In [21]:
# 24. Troca de colunas (fácil)
# Troque as colunas 0 e 2 de A = np.arange(12).reshape(3,4) sem copiar (sempre que possível).
A_troca = np.arange(12).reshape(3, 4)
print(f"Matriz A original:\n{A_troca}")

A_trocada = A_troca[:, [2, 1, 0, 3]]

print(f"Matriz A com colunas 0 e 2 trocadas (usando indexação avançada, que faz uma cópia):\n{A_trocada}")


Matriz A original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Matriz A com colunas 0 e 2 trocadas (usando indexação avançada, que faz uma cópia):
[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]
