<a href="https://colab.research.google.com/github/COAP230023/atividade-praticas-em-numpy-gabrieltizziani/blob/main/Atividade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Treino de NumPy — 42 exercícios hands-on

**Objetivo:** praticar manipulação de arrays NumPy (criação, slicing, broadcasting, álgebra linear, estatística, datas, strides).

**Regras:** use **apenas** NumPy (`import numpy as np`). Para reprodutibilidade, prefira `np.random.default_rng(seed)`.


In [8]:
### 1. Vetor de zeros  _(fácil)_

### Crie um array 1D com 10 zeros usando NumPy e mostre o dtype e o shape.

import numpy

# Criar um vetor 1D com 10 zeros
array = numpy.zeros(10)

# Exibir o array, dtype e shape
print(array)
print("dtype:", array.dtype)
print("shape:", array.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
dtype: float64
shape: (10,)


In [10]:
### 2. Vetor de uns  _(fácil)_

### Crie um array 1D com 10 uns e transforme-o em float64.
import numpy as np
numpy.ones(10, dtype=np.float64)



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
### 3. Sequência 0–9  _(fácil)_

### Crie um array com os inteiros de 0 a 9 (inclusive).
import numpy as np
np.arange(10)

#arange cria um array de valores espaçados uniformemente dentro de um intervalo definido


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
### 4. Matriz 3×3 com 0…8  _(fácil)_

### Crie um array 3×3 com os valores 0…8 (reshape).
import numpy as np
np.arange(9).reshape(3, 3)

In [ ]:
### 5. Índices não zero  _(fácil)_

### Dado o vetor v = np.array([1,2,0,0,4,0])`, encontre os índices dos elementos não nulos.
import numpy as np
v = np.array([1, 2, 0, 0, 4, 0])
elementos_nao_nulos = np.nonzero(v)
print(elementos_nao_nulos)


In [ ]:
### 6. Linspace  _(fácil)_

### Crie um vetor de 12 pontos igualmente espaçados no intervalo [0, 1].
numpy.linspace(0, 1, 12)


In [13]:
### 7. Identidade 5×5  _(fácil)_

### Crie uma matriz identidade de ordem 5.
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
### 8. Aleatórios 3×3×3  _(fácil)_

### Gere um array 3×3×3 com valores aleatórios uniformes em [0,1). Use `np.random.default_rng(42)`.
rng = np.random.default_rng(42)
array_3x3x3 = rng.random((3, 3, 3))
print(array_3x3x3)




In [ ]:
### 9. Min/Max  _(fácil)_

### Crie uma matriz 10×10 de aleatórios uniformes e mostre o valor mínimo e máximo.
matriz_10x10 = np.random.rand(10, 10)
min_val = matriz_10x10.min()
max_val = matriz_10x10.max()
print(f"Valor Mínimo: {min_val}")
print(f"Valor Máximo: {max_val}")

In [ ]:
### 10. Padronização 1D  _(fácil)_

### Dado `x = [1,2,3,4,5]`, crie um array float e normalize para média 0 e desvio 1.

x = np.array([1, 2, 3, 4, 5], dtype=float)
media = x.mean()
desvio = x.std()
x_padronizado = (x - media) / desvio
print(f"Array original: {x}")
print(f"Média original: {x.mean():.2f}, Desvio original: {x.std():.2f}")
print(f"Array padronizado: {x_padronizado}")
print(f"Média padronizada: {x_padronizado.mean():.2f}, Desvio padronizado: {x_padronizado.std():.2f}")

In [14]:
### 11. Conversão de tipos  _(fácil)_

### Converta `np.array([1,2,3])` (int32) para float32 e depois para int64.
arr_int32 = np.array([1, 2, 3])
print(f"Original: {arr_int32}, Tipo: {arr_int32.dtype}")

arr_float32 = arr_int32.astype(np.float32)
print(f"Para float32: {arr_float32}, Tipo: {arr_float32.dtype}")

arr_int64 = arr_float32.astype(np.int64)
print(f"Para int64: {arr_int64}, Tipo: {arr_int64.dtype}")

Original: [1 2 3], Tipo: int64
Para float32: [1. 2. 3.], Tipo: float32
Para int64: [1 2 3], Tipo: int64


In [ ]:
### 12. Clipping  _(fácil)_

### Dado `a = [2, 5, 7, 1, 9]`, limite os valores ao intervalo [0,5] (valores acima de 5 tornam-se 5).
a = np.array([2, 5, 7, 1, 9])
a_clipped = np.clip(a, 0, 5)
print(f"Array original: {a}")
print(f"Array limitado [0,5]: {a_clipped}")

In [ ]:
### 13. Inversão  _(fácil)_

### Crie um vetor de 0 a 9 e inverta a ordem (sem usar `[::-1]`).

vetor = np.arange(10)
vetor_invertido = np.flip(vetor)
print(f"Vetor original: {vetor}")
print(f"Vetor invertido: {vetor_invertido}")

In [ ]:
### 14. Empilhamento  _(fácil)_

### Dado `a = [1,2,3]` e `b = [4,5,6]`, empilhe horizontal e verticalmente.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
empilhado_h = np.hstack((a, b))
empilhado_v = np.vstack((a, b))
print(f"a: {a}, b: {b}")
print(f"Horizontal: {empilhado_h}")
print(f"Vertical:\n{empilhado_v}")


In [ ]:
### 15. Diagonal  _(fácil)_

### Crie uma matriz 4×4 com a diagonal principal igual a 5 e as demais entradas zero.
diagonal_5 = np.diag([5, 5, 5, 5])
print(diagonal_5)

In [15]:
### 16. Somas por eixo  _(fácil)_

### Para a matriz `A = np.arange(12).reshape(3,4)`, calcule a soma por linhas e por colunas.
A = np.arange(12).reshape(3, 4)
soma_por_colunas = A.sum(axis=0)
soma_por_linhas = A.sum(axis=1)
print(f"Matriz A:\n{A}")
print(f"Soma por colunas (axis=0): {soma_por_colunas}")
print(f"Soma por linhas (axis=1): {soma_por_linhas}")

Matriz A:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Soma por colunas (axis=0): [12 15 18 21]
Soma por linhas (axis=1): [ 6 22 38]


In [16]:
### 17. Frequências inteiras  _(fácil)_

### Gere 100 inteiros aleatórios em [0,9] e conte as frequências de cada valor (0 a 9).
rng = np.random.default_rng(42)
dados = rng.integers(0, 10, size=100) # [0, 10)
valores, contagens = np.unique(dados, return_counts=True)

print("Frequências (Valor: Contagem):")
for v, c in zip(valores, contagens):
    print(f"{v}: {c}", end=" | ")
print() # Nova linha


Frequências (Valor: Contagem):
0: 9 | 1: 9 | 2: 6 | 3: 9 | 4: 15 | 5: 7 | 6: 11 | 7: 15 | 8: 12 | 9: 7 | 


In [45]:
### 18. Slicing com passo  _(fácil)_

### Dado `v = np.arange(20)`, selecione cada 3º elemento começando do índice 1.
v = np.arange(20)
v_filtrado = v[1::3]
print(f"Vetor original: {v}")
print(f"Elementos a partir do índice 1 com passo 3: {v_filtrado}")


Vetor original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elementos a partir do índice 1 com passo 3: [ 1  4  7 10 13 16 19]


In [18]:
# 18. Slicing com passo (fácil)
# Dado v = np.arange(20), selecione cada 3º elemento começando do índice 1.

v = np.arange(20)
v_filtrado = v[1::3]
print(f"Vetor original: {v}")
print(f"Elementos a partir do índice 1 com passo 3: {v_filtrado}")

Vetor original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elementos a partir do índice 1 com passo 3: [ 1  4  7 10 13 16 19]


In [ ]:
# 19. Máscara booleana (fácil)
# Crie uma máscara para números pares de 0…19 e use-a para filtrar o vetor.
vetor_0_19 = np.arange(20)
mascara_par = (vetor_0_19 % 2 == 0)
vetor_pares = vetor_0_19[mascara_par]
print(f"Vetor 0-19: {vetor_0_19}")
# print(f"Máscara booleana: {mascara_par}")
print(f"Números pares: {vetor_pares}")


In [ ]:
# 20. Lista de listas -> array (fácil)
# Converta [[1,2,3],[4,5,6]] em ndarray, verifique shape e dtype.
print("--- 20. Lista de listas -> array ---")
lista_de_listas = [[1, 2, 3], [4, 5, 6]]
array_convertido = np.array(lista_de_listas)
print(f"Lista de listas: {lista_de_listas}")
print(f"Array convertido:\n{array_convertido}")
print(f"Shape: {array_convertido.shape}")
print(f"Dtype: {array_convertido.dtype}")
print("-" * 30)

In [ ]:
# 21. Datas básicas (fácil)
# Crie um array de datas diárias de 2025-01-01 a 2025-01-07 (inclusive).
print("--- 21. Datas básicas ---")
datas = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
print(datas)
print("-" * 30)

In [19]:
# 22. Centralizar colunas (fácil)
# Dada A = np.array([[1.,2.,3.],[4.,5.,6.]]), subtraia a média de cada coluna.
A = np.array([[1., 2., 3.], [4., 5., 6.]])
medias_colunas = A.mean(axis=0)
A_centralizada = A - medias_colunas
print(f"Matriz A:\n{A}")
print(f"Médias das colunas: {medias_colunas}")
print(f"Matriz A centralizada (Média de cada coluna deve ser ~0):\n{A_centralizada}")
print(f"Novas médias: {A_centralizada.mean(axis=0)}") # Deve ser muito próximo de zero


Matriz A:
[[1. 2. 3.]
 [4. 5. 6.]]
Médias das colunas: [2.5 3.5 4.5]
Matriz A centralizada (Média de cada coluna deve ser ~0):
[[-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]]
Novas médias: [0. 0. 0.]


In [20]:
# 23. Produto elemento-a-elemento vs. escalar (fácil)
# Dadas a=[1,2,3] e b=[4,5,6], calcule produto elemento a elemento e o produto escalar.
a_prod = np.array([1, 2, 3])
b_prod = np.array([4, 5, 6])

prod_element_a_element = a_prod * b_prod
prod_escalar = np.dot(a_prod, b_prod)

print(f"a: {a_prod}, b: {b_prod}")
print(f"Produto elemento-a-elemento (a * b): {prod_element_a_element}")
print(f"Produto escalar (np.dot(a, b)): {prod_escalar}")

a: [1 2 3], b: [4 5 6]
Produto elemento-a-elemento (a * b): [ 4 10 18]
Produto escalar (np.dot(a, b)): 32


In [49]:
# 24. Troca de colunas (fácil)
# Troque as colunas 0 e 2 de A = np.arange(12).reshape(3,4) sem copiar (sempre que possível).
A_troca = np.arange(12).reshape(3, 4)
print(f"Matriz A original:\n{A_troca}")

A_trocada = A_troca[:, [2, 1, 0, 3]]

print(f"Matriz A com colunas 0 e 2 trocadas (usando indexação avançada, que faz uma cópia):\n{A_trocada}")


Matriz A original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Matriz A com colunas 0 e 2 trocadas (usando indexação avançada, que faz uma cópia):
[[ 2  1  0  3]
 [ 6  5  4  7]
 [10  9  8 11]]


In [52]:
SEED = 42
rng = np.random.default_rng(SEED)
# 25. Flatten vs. ravel (médio)
matriz = np.arange(6).reshape(2, 3)
print(f"Original:\n{matriz}")

flat_copy = matriz.flatten()
flat_copy[0] = 999
print(f"\nflat_copy (CÓPIA) modificado. Original (NÃO) muda:\n{matriz}")

matriz = np.arange(6).reshape(2, 3)
ravel_view = matriz.ravel()
ravel_view[0] = 888
print(f"\nravel_view (VIEW) modificado. Original (MUDOU):\n{matriz}")


Original:
[[0 1 2]
 [3 4 5]]

flat_copy (CÓPIA) modificado. Original (NÃO) muda:
[[0 1 2]
 [3 4 5]]

ravel_view (VIEW) modificado. Original (MUDOU):
[[888   1   2]
 [  3   4   5]]


In [53]:
# 26. Tabuleiro 8x8 (médio)
# Crie uma matriz 8x8 com padrão de tabuleiro (0 e 1 alternados).
indices = np.arange(8)
matriz_i, matriz_j = np.meshgrid(indices, indices)

tabuleiro = (matriz_i + matriz_j) % 2
print(tabuleiro)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [54]:
# 27. np.where condicional (médio)
# Dado x = np.arange(-5,6), substitua negativos por 0 e mantenha não-negativos.
x = np.arange(-5, 6)
x_modificado = np.where(x < 0, 0, x)
print(f"Original: {x}")
print(f"Modificado: {x_modificado}")

Original: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
Modificado: [0 0 0 0 0 0 1 2 3 4 5]


In [55]:
# 28. Precisão de média (médio)
# Gere 1_000_000 floats uniformes em [0,1) e compute a média.
# Compare com o valor teórico 0.5 (erro absoluto).
N = 1_000_000
dados = rng.random(N)
media_calculada = dados.mean()
media_teorica = 0.5
erro_absoluto = np.abs(media_calculada - media_teorica)

print(f"Média calculada: {media_calculada}")
print(f"Média teórica: {media_teorica}")
print(f"Erro absoluto: {erro_absoluto:.6e}")

Média calculada: 0.5000264761740889
Média teórica: 0.5
Erro absoluto: 2.647617e-05


In [56]:
# 29. Produto cartesiano (broadcasting) (médio)
# Dado a=[1,2,3] e b=[10,20,30,40], gere todas as somas possíveis a_i + b_j via broadcasting (matriz 3x4).
a = np.array([1, 2, 3])
b = np.array([10, 20, 30, 40])

# Transforma 'a' em coluna (3, 1) para broadcasting com 'b' (1, 4)
a_coluna = a[:, np.newaxis]
somas = a_coluna + b

print(f"a (3,1): {a_coluna.shape}")
print(f"b (1,4): {b.shape}")
print(f"Somas (3x4):\n{somas}")


a (3,1): (3, 1)
b (1,4): (4,)
Somas (3x4):
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [47]:
# 30. Convolução 1D simples (médio)
# Implemente uma convolução 1D 'valid' de um sinal s por um kernel k
# usando np.flip e np.lib.stride_tricks.sliding_window_view (sem np.convolve).
from numpy.lib.stride_tricks import sliding_window_view
s = np.array([1, 2, 3, 4, 5, 6])
k = np.array([1, 0, -1])

k_flip = np.flip(k)

janelas = sliding_window_view(s, window_shape=len(k))

convolucao = (janelas * k_flip).sum(axis=1)

print(f"Sinal (s): {s}")
print(f"Kernel (k): {k}")
print(f"Resultado (valid): {convolucao}")

Sinal (s): [1 2 3 4 5 6]
Kernel (k): [ 1  0 -1]
Resultado (valid): [2 2 2 2]


In [ ]:
# 31. Normalização min–max por coluna (médio)
# Dada A = rng.normal(size=(5,4)), normalize cada coluna para o intervalo [0,1],
# tratando colunas constantes.
A = rng.normal(size=(5, 4))
A[:, 0] = 5.0
print(f"Matriz A (5x4) (Coluna 0 constante):\n{A}")

min_col = A.min(axis=0)
max_col = A.max(axis=0)
intervalo = max_col - min_col

A_norm = np.zeros_like(A)

mascara_nao_constante = intervalo != 0

A_norm[:, mascara_nao_constante] = \
    (A[:, mascara_nao_constante] - min_col[mascara_nao_constante]) / \
    intervalo[mascara_nao_constante]

print(f"Matriz A Normalizada [0,1]:\n{A_norm}")

In [ ]:
# 32. Ordenar por coluna (médio)
# Ordene as linhas de A = np.array([[3,9],[1,4],[2,5]]) pelo valor crescente da 2ª coluna.
A = np.array([[3, 9], [1, 4], [2, 5]])

indices_ordenados = np.argsort(A[:, 1])

A_ordenada = A[indices_ordenados]

print(f"Matriz original:\n{A}")
print(f"Matriz ordenada pela 2ª coluna:\n{A_ordenada}")

In [ ]:
# 33. Únicos + contagens + primeira ocorrência (médio)
# Para x = [3,1,2,3,2,3,1], obtenha valores únicos, contagens e índice da primeira ocorrência de cada valor.
x = np.array([3, 1, 2, 3, 2, 3, 1])

unicos, indices_primeira_ocorrencia, contagens = np.unique(x, return_counts=True, return_index=True)

print(f"Vetor x: {x}")
print(f"Valores únicos: {unicos}")
print(f"Contagens: {contagens}")
print(f"Índice da 1ª ocorrência: {indices_primeira_ocorrencia}")

In [ ]:
# 34. Matriz de distâncias 2D (médio)
# Dada P com N pontos 2D, compute a matriz NxN de distâncias euclidianas sem loops explícitos
P = np.array([[0, 0], [1, 0], [0, 1], [1, 1]])

diferencas_quadrado = (P[np.newaxis, :] - P[:, np.newaxis])**2


soma_quadrado = diferencas_quadrado.sum(axis=2)

matriz_distancias = np.sqrt(soma_quadrado)

print(f"Pontos P:\n{P}")
print(f"Matriz de Distâncias Euclidianas:\n{matriz_distancias}")


In [26]:
# 35. Covariância e correlação (médio)
# Simule uma matriz 1000x3 de N(0,1) e compute cov (colunas como variáveis) e corrcoef.
print("\n--- 35. Covariância e correlação ---")
dados_normais = rng.normal(loc=0.0, scale=1.0, size=(1000, 3))

matriz_cov = np.cov(dados_normais, rowvar=False)

matriz_corr = np.corrcoef(dados_normais, rowvar=False)

print(f"Matriz de Covariância (3x3):\n{matriz_cov.round(4)}")
print(f"\nMatriz de Correlação (3x3):\n{matriz_corr.round(4)}")
print("-" * 30)


--- 35. Covariância e correlação ---
Matriz de Covariância (3x3):
[[ 1.0281  0.0034 -0.0303]
 [ 0.0034  0.9969  0.0635]
 [-0.0303  0.0635  1.0227]]

Matriz de Correlação (3x3):
[[ 1.      0.0034 -0.0295]
 [ 0.0034  1.      0.0629]
 [-0.0295  0.0629  1.    ]]
------------------------------


In [27]:
# 36. One-hot encoding (médio)
# Converta os rótulos y = [2,0,1,2] em codificação one-hot usando apenas operações NumPy.
y = np.array([2, 0, 1, 2])
num_classes = y.max() + 1


one_hot = np.zeros((len(y), num_classes), dtype=int)

one_hot[np.arange(len(y)), y] = 1

print(f"Rótulos: {y}")
print(f"One-hot encoding:\n{one_hot}")




Rótulos: [2 0 1 2]
One-hot encoding:
[[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]


In [30]:
# 37. k-means 2D (NumPy puro) (difícil)
# Implemente k-means com K=3 em pontos 2D: inicialize centróides aleatórios,
# faça 10 iterações de (1) atribuir pontos ao centróide mais próximo e (2) recomputar centróides.
print("\n--- 37. k-means 2D (NumPy puro) ---")
K = 3
N_POINTS = 100

# Geração dos dados de exemplo
data = np.vstack([
    rng.normal(loc=[2, 2], scale=1, size=(N_POINTS // 3, 2)),
    rng.normal(loc=[-2, -2], scale=1, size=(N_POINTS // 3, 2)),
    rng.normal(loc=[2, -2], scale=1, size=(N_POINTS - 2 * (N_POINTS // 3), 2))
])

indices_iniciais = rng.choice(len(data), K, replace=False)
centroids = data[indices_iniciais]

MAX_ITER = 10
for i in range(MAX_ITER):

    diff_sq = (data[:, np.newaxis, :] - centroids[np.newaxis, :, :])**2
    distances_sq = diff_sq.sum(axis=2)

    labels = np.argmin(distances_sq, axis=1)

    new_centroids = np.zeros_like(centroids)
    for k in range(K):
        cluster_points = data[labels == k]

        if len(cluster_points) > 0:

            new_centroids[k] = cluster_points.mean(axis=0)
        else:
            new_centroids[k] = centroids[k]

    if np.allclose(centroids, new_centroids):
        print(f"Convergiu na iteração {i+1}")
        break

    centroids = new_centroids

print(f"Centróides finais (após {i+1} iterações):\n{centroids.round(4)}")
print("-" * 30)


--- 37. k-means 2D (NumPy puro) ---
Convergiu na iteração 6
Centróides finais (após 6 iterações):
[[ 1.6523 -2.1225]
 [ 1.9811  2.0845]
 [-1.8427 -2.1473]]
------------------------------


In [44]:
# 38. PCA básica (autovetores) (difícil)
# Implemente PCA 2D→1D: centralize X (N×2), calcule covariância, autovetores,
# projete em 1D e reconstrua aproximado.
print("\n--- 38. PCA básica (autovetores) ---")
# Dados de exemplo 2D (correlacionados)
X = rng.multivariate_normal(mean=[0, 0], cov=[[10, 5], [5, 2]], size=100)
N, D = X.shape

X_mean = X.mean(axis=0)
X_centered = X - X_mean

Cov = np.cov(X_centered, rowvar=False)

# 3. Autovalores e Autovetores
# Autovetores são retornados como COLUNAS da matriz V (no NumPy)
eigen_values, eigen_vectors = np.linalg.eigh(Cov)

# 4. Seleciona o principal componente (autovetor com maior autovalor)
# np.argsort ordena do menor para o maior. Pegamos o último índice [::-1][0]
idx_principal = np.argsort(eigen_values)[::-1][0]
principal_component = eigen_vectors[:, idx_principal] # Shape (2,)

# 5. Projeção 2D -> 1D
# X_centered (100, 2) @ principal_component (2, 1) = X_projected (100, 1)
X_projected = X_centered @ principal_component

# 6. Reconstrução aproximada 1D -> 2D
# X_reconstructed (100, 1) @ principal_component.T (1, 2) + X_mean (2,)
X_reconstructed = X_projected[:, np.newaxis] @ principal_component[np.newaxis, :] + X_mean

print(f"Matriz de Covariância:\n{Cov.round(4)}")
print(f"Autovetor Principal: {principal_component.round(4)}")
print(f"Dimensões de X_projected: {X_projected.shape}")
print(f"Primeiros 5 pontos reconstruídos:\n{X_reconstructed[:5].round(2)}")


--- 38. PCA básica (autovetores) ---
Matriz de Covariância:
[[9.5497 4.4098]
 [4.4098 2.6234]]
Autovetor Principal: [-0.8993 -0.4372]
Dimensões de X_projected: (100,)
Primeiros 5 pontos reconstruídos:
[[-0.63 -0.23]
 [ 1.24  0.68]
 [-2.44 -1.11]
 [ 4.58  2.3 ]
 [ 3.6   1.82]]


/tmp/ipython-input-1837817148.py:6: RuntimeWarning: covariance is not symmetric positive-semidefinite.
  X = rng.multivariate_normal(mean=[0, 0], cov=[[10, 5], [5, 2]], size=100)


In [39]:
# 39. Convolução 2D (im2col) (difícil)
# Implemente convolução 2D 'valid' de uma imagem I por um kernel K
# usando sliding_window_view para gerar blocos e multiplicação matricial.
from numpy.lib.stride_tricks import sliding_window_view
# Imagem de exemplo 5x5
I = np.arange(25).reshape(5, 5).astype(float)
# Kernel de exemplo 3x3
K = np.array([[1, 0, -1], [2, 0, -2], [1, 0, -1]]).astype(float)
K_h, K_w = K.shape

# 1. Usa sliding_window_view para obter todos os blocos KxK (im2col)
# O shape será (H_out, W_out, K_h, K_w)
janelas_2d = sliding_window_view(I, window_shape=K.shape)

# 2. Achata o Kernel (para o vetor de pesos)
# Kernel shape (K_h * K_w, 1)
K_flat = K.ravel()

# 3. Achata as janelas (para o vetor de entrada)
# janelas_2d shape (H_out, W_out, K_h, K_w) -> (H_out * W_out, K_h * K_w)
H_out, W_out, _, _ = janelas_2d.shape
janelas_flat = janelas_2d.reshape(H_out * W_out, K_h * K_w)

# 4. Multiplicação matricial (Convolução)
# (H_out * W_out, K*K) @ (K*K, 1) = (H_out * W_out, 1)
conv_flat = janelas_flat @ K_flat

# 5. Remodela o resultado para o shape de saída
conv_2d = conv_flat.reshape(H_out, W_out)

print(f"Imagem I (5x5):\n{I}")
print(f"Kernel K (3x3):\n{K}")
print(f"Convolução 2D 'valid' ({H_out}x{W_out}):\n{conv_2d}")

Imagem I (5x5):
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]]
Kernel K (3x3):
[[ 1.  0. -1.]
 [ 2.  0. -2.]
 [ 1.  0. -1.]]
Convolução 2D 'valid' (3x3):
[[-8. -8. -8.]
 [-8. -8. -8.]
 [-8. -8. -8.]]
------------------------------


In [40]:
# 40. Sistemas lineares e resíduo (difícil)
# Gere uma matriz A (100x100) bem-condicionada, um vetor b e resolva Ax=b com
# np.linalg.solve. Compute o resíduo relativo ||Ax−b||/||b|| e cond(A).
N_EQ = 100

# 1. Cria uma matriz A bem-condicionada (ex: matriz aleatória + diagonal forte)
A_base = rng.standard_normal(size=(N_EQ, N_EQ))
A = A_base + N_EQ * np.eye(N_EQ) # Garante que seja bem-condicionada e invertível

# 2. Gera o vetor b (aleatório)
b = rng.standard_normal(N_EQ)

# 3. Resolve Ax = b
x = np.linalg.solve(A, b)

# 4. Calcula o resíduo: ||Ax - b||
residuos = A @ x - b
norm_residuos = np.linalg.norm(residuos)

# 5. Calcula a norma de b: ||b||
norm_b = np.linalg.norm(b)

# 6. Resíduo Relativo: ||Ax - b|| / ||b||
residuo_relativo = norm_residuos / norm_b

# 7. Número de condição de A
cond_A = np.linalg.cond(A)

print(f"Resíduo Relativo (||Ax-b||/||b||): {residuo_relativo:.2e}")
print(f"Número de Condição cond(A): {cond_A:.2f}")
# O resíduo relativo deve ser muito pequeno (próximo à precisão da máquina)


--- 40. Sistemas lineares e resíduo ---
Resíduo Relativo (||Ax-b||/||b||): 3.41e-16
Número de Condição cond(A): 1.31
------------------------------


In [41]:
# 41. Regressão linear (OLS) com NumPy (difícil)
# Dado X (Nxd) e y, calcule os coeficientes OLS usando np.linalg.lstsq e avalie RMSE no treino.
N_SAMPLES = 100
D_FEAT = 2

# Dados de exemplo: y = 2*x1 - 1.5*x2 + 5 + ruído
X = rng.random(size=(N_SAMPLES, D_FEAT))
true_coeffs = np.array([2.0, -1.5])
y_true = X @ true_coeffs + 5.0
y = y_true + rng.normal(0, 0.1, N_SAMPLES)

# 1. Adiciona o termo de intercepto (coluna de uns)
# X_pad (N, D+1)
X_pad = np.hstack([X, np.ones((N_SAMPLES, 1))])

# 2. Resolve OLS: coeficientes = (X^T @ X)^(-1) @ X^T @ y
# Usa np.linalg.lstsq (Least Squares) para solução robusta (preferível a inversão direta)
# Retorna (coeficientes, soma dos quadrados dos resíduos, posto, valores singulares)
coeffs, residuals_sum_sq, rank, s = np.linalg.lstsq(X_pad, y, rcond=None)
# coeffs[0:D] são os pesos, coeffs[D] é o intercepto

# 3. Predição
y_pred = X_pad @ coeffs

# 4. Avalia RMSE no treino
rmse = np.sqrt(np.mean((y - y_pred)**2))

print(f"Coeficientes OLS (Pesos, Intercepto): {coeffs.round(4)}")
print(f"RMSE (Root Mean Square Error) no treino: {rmse:.4f}")


--- 41. Regressão linear (OLS) com NumPy ---
Coeficientes OLS (Pesos, Intercepto): [ 1.9772 -1.4828  4.9844]
RMSE (Root Mean Square Error) no treino: 0.0888
------------------------------


In [48]:
# 42. Rolling window 2D com strides (difícil)
# Usando sliding_window_view, compute a média local 3x3 de uma imagem 2D sem laços explícitos.

img = np.arange(36).reshape(6, 6)
WINDOW_SIZE = (3, 3)

windows = sliding_window_view(img, window_shape=WINDOW_SIZE)

media_movel = windows.mean(axis=(-2, -1))

print(f"Imagem Original (6x6):\n{img}")
print(f"\nMédia 3x3 Rolling Window (4x4):\n{media_movel.round(2)}")

Imagem Original (6x6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

Média 3x3 Rolling Window (4x4):
[[ 7.  8.  9. 10.]
 [13. 14. 15. 16.]
 [19. 20. 21. 22.]
 [25. 26. 27. 28.]]
